- src/components/common/AllMemberInfoTable/index.tsx
- src/components/common/Header/HeaderLeftCol.tsx
- src/components/common/Header/HeaderRightCol.tsx
- src/components/common/PaymentStatusInfoTable/PaymentStatusInfoTableBody.tsx
- src/components/common/PaymentStatusInfoTable/PaymentStatusInfoTableHeader.tsx
- src/components/common/PaymentStatusInfoTable/index.tsx
- src/components/common/Title.tsx
- src/constants/common.ts
- src/constants/table.ts
- src/pages/PaymentStatusPage.tsx
- src/routes/Router.tsx
- src/routes/routePath.ts
- src/types/entities/member.ts
> [Feature/#12] 회비 납부 여부 관리 페이지 레이아웃 구현

- src/components/common/AllMemberInfoTable/AllMemberInfoTableBody.tsx
- src/components/common/AllMemberInfoTable/AllMemberInfoTableHeader.tsx
- src/components/common/Header/HeaderRightCol.tsx
- src/components/common/InfoModal/AcceptMemberListModal/index.tsx
- src/components/common/InfoModal/EditInfoModal/SecondRow.tsx
- src/components/common/InfoModal/EditInfoModal/index.tsx
- src/components/common/InfoModal/MemberDetailInfoModal/index.tsx
- src/components/common/PaymentStatusInfoTable/PaymentStatusInfoTableBody.tsx
- src/components/common/PaymentStatusInfoTable/PaymentStatusInfoTableHeader.tsx
- src/components/common/PendingMemberInfoTable/PendingMemberInfoTableBody.tsx
- src/components/common/PendingMemberInfoTable/PendingMemberInfoTableHeader.tsx
- src/components/common/Title.tsx
- src/components/layout/sidebar/NavigateButton.tsx
- src/components/layout/sidebar/Sidebar.tsx
- src/components/layout/sidebar/SidebarListButton.tsx
- src/styles/palette.ts
- src/styles/theme.ts
- src/styles/typo.ts
색상값, 타이포를 직접 입력하는 방식으로 코드가 작성되어있었습니다.
styles 폴더 내부 상수 값으로 선언해서 사용하도록 리팩토링했습니다.
> [Refactor/#25] style 관련 코드 리팩토링

- .eslintrc.cjs
- src/apis/allMemberApi.ts
- src/apis/pendingMemberApi.ts
- src/components/common/Header/HeaderLeftCol.tsx
- src/components/common/Header/HeaderRightCol.tsx
- src/components/common/Header/index.tsx
- src/components/common/InfoModal/AcceptMemberListModal/index.tsx
- src/components/common/InfoModal/EditInfoModal/index.tsx
- src/components/common/PendingMemberInfoTable/index.tsx
- src/components/common/Title.tsx
- src/constants/table.ts
- src/hooks/queries/useGetPendingMemberListQuery.ts
- src/pages/PendingMembersPage.tsx
가입 대기 멤버 관리 페이지 검색 기능 추가해놨습니다.
추후 회비 납부 멤버 관리 쪽까지 같이 구현하고 나서 좀 리팩토링해볼게요..
> [Feature/#20] 대기 멤버 관리 페이지 검색 api 연결

- src/apis/paymentStatusApi.ts
- src/components/common/Header/HeaderLeftCol.tsx
- src/components/common/Header/index.tsx
- src/components/common/PaymentStatusInfoTable/index.tsx
- src/constants/table.ts
- src/hooks/queries/useGetPaymentStatusMemberListQuery.ts
- src/pages/PaymentStatusMembersPage.tsx
> [Feature/#21] 회비 납부 여부 페이지 검색 api 연결

- src/components/common/InfoModal/AcceptMemberListModal/index.tsx
- src/components/common/InfoModal/MemberDetailInfoModal/index.tsx
> [Design/#32]: 디자인 수정 사항 반영

- src/components/common/InfoModal/AcceptMemberListModal/index.tsx
- vercel.json
객체 예외 처리를 안 해주어 런타임 에러 나는 부분 해결해뒀습니다.
> [Bug/#39] 런타임 에러 해결

- src/components/common/InfoModal/AcceptMemberListModal/index.tsx
- vercel.json
- vite.config.ts
배포 사이트에서 새로 고침 시 흰 화면이 뜨는 문제 해결합니다...
> [Bug/#39] 배포 사이트에서 새로 고침 시 흰 화면이 뜨는 문제 해결

- src/components/common/InfoModal/AcceptMemberListModal/index.tsx
- vercel.json
- vite.config.ts
배포 시 public 폴더 경로로 불러오지 못하는 문제 해결
> [Bug/#39] 배포 시 public 폴더 경로로 불러오지 못하는 문제 해결

- src/apis/allMemberApi.ts
- src/apis/grantableMemberApi.ts
- src/apis/paymentStatusApi.ts
- src/apis/pendingMemberApi.ts
- src/components/common/Table/AllMemberInfoTable/index.tsx
- src/components/common/Table/GrantableMemberInfoTable/index.tsx
- src/components/common/Table/PaymentStatusInfoTable/index.tsx
- src/components/common/Table/PendingMemberInfoTable/index.tsx
- src/hooks/queries/useGetAllMemberListQuery.ts
- src/hooks/queries/useGetGrantableMemberListQuery.ts
- src/hooks/queries/useGetPaymentStatusMemberListQuery.ts
- src/hooks/queries/useGetPendingMemberListQuery.ts
- src/pages/AllMembersPage.tsx
- src/pages/GrantableMembersPage.tsx
- src/pages/PaymentStatusMembersPage.tsx
- src/pages/PendingMembersPage.tsx
- src/routes/Router.tsx
- src/types/dtos/member.ts
QA 후 반영되어야 하는 사항이 있어 반영했습니다.
페이지네이션 페이지 넘어가는 동작 안 하는 부분 수정
맨 처음 접속 시 전체 멤버 관리 페이지로 내비게이션 되도록 수정
각 페이지 멤버 관리 설명 추가
> [Bug/#50] QA 수정 사항 반영

- src/apis/grantedMemberApi.ts
- src/components/common/Header/HeaderLeftCol.tsx
- src/components/common/Header/index.tsx
- src/components/common/Table/GrantedMemberInfoTable/GrantedMemberInfoTableBody.tsx
- src/components/common/Table/GrantedMemberInfoTable/GrantedMemberInfoTableHeader.tsx
- src/components/common/Table/GrantedMemberInfoTable/index.tsx
- src/constants/common.ts
- src/constants/queryKey.ts
- src/hooks/queries/useGetGrantedMemberListQuery.ts
- src/pages/GrantedMembersPage.tsx
- src/routes/Router.tsx
- src/routes/routePath.ts
- src/types/entities/member.ts
승인 멤버 관리 페이지 레이아웃 구현 및 api 연결했습니다.
> [Feature/#52] 승인 멤버 관리 페이지 레이아웃 구현 및 api 연결

- src/components/common/Table/PaymentStatusInfoTable/PaymentStatusInfoTableBody.tsx
- src/constants/table.ts
> [Bug/#54] 회비 납부 여부 처리 방식 변경

- src/components/common/Header/HeaderRightCol.tsx
배포 에러 해결했습니다.
HeaderRightElement에 반환값을 Record<ManagementVariant, ReactElement | null>로 지정해주었는데 모든 variant에 대해서 정의를 해주지 않아 발생한 문제입니다.
해결해서 올려놨습니다.
> [Bug/#58] 배포 에러 해결 (모든 variant에 대해서 반환값을 지정해주도록 변경)

- src/components/common/Table/AllMemberInfoTable/AllMemberInfoTableBody.tsx
- src/components/common/Table/GrantableMemberInfoTable/GrantableMemberInfoTableBody.tsx
- src/components/common/Table/GrantedMemberInfoTable/GrantedMemberInfoTableBody.tsx
- src/components/common/Table/PaymentStatusInfoTable/PaymentStatusInfoTableBody.tsx
- src/components/common/Table/PendingMemberInfoTable/PendingMemberInfoTableBody.tsx
- src/pages/SigninPage.tsx
- src/routes/Router.tsx
자잘한 수정 사항을 반영합니다.
- 학과 필드 단어 단위로 줄바꿈되도록 수정
- 파일명 변경
> [Refactor/#57] 자잘한 수정 사항 반영

- src/pages/SigninPage.tsx
> [Refactor/#57] 자잘한 수정 사항 반영 및 에러 해결

- src/apis/index.ts
- src/components/layout/common/Layout.tsx
- src/hooks/useAuthSuccessRedirectPage.ts
- src/pages/AuthSuccessRedirectPage.tsx
- src/pages/SigninPage.tsx
- src/routes/Router.tsx
소셜 로그인으로 변경하는 과정에서 누락된 파일이 있어 추가했습니다.
> [Refactor/#65] 기본 로그인에서 깃허브 소셜 로그인으로 변경

- src/apis/allMemberApi.ts
- src/apis/index.ts
- src/components/common/InfoModal/EditInfoModal/index.tsx
- src/components/layout/common/Layout.tsx
- src/hooks/mutations/useEditMemberInfoMutation.ts
- src/hooks/useAuthSuccessRedirectPage.ts
- src/pages/AuthSuccessRedirectPage.tsx
- src/pages/SigninPage.tsx
- src/routes/Router.tsx
- src/types/entities/member.ts
멤버 정보 수정 시 빈 필드는 빈 문자열 대신 null 입력하도록 수정했습니다.
서버에서 디스코드 닉네임과 사용자명이 빈 필드이면 null로 요청을 보내달라고 하여 수정했습니다.
> [Bug/#68] 멤버 정보 수정 시 빈 필드는 빈 문자열 대신 null 입력하도록 수정

- src/apis/allMemberApi.ts
- src/apis/index.ts
- src/components/common/InfoModal/EditInfoModal/ThirdRow.tsx
- src/components/common/InfoModal/EditInfoModal/index.tsx
- src/components/layout/common/Layout.tsx
- src/hooks/mutations/useEditMemberInfoMutation.ts
- src/pages/SigninPage.tsx
- src/types/entities/member.ts
로그아웃 기능 추가해뒀고, 토큰 만료 시 처리도 추가해뒀습니다.
> [Feature/#71] 로그아웃 기능 및 토큰 만료 처리 추가

- src/apis/allMemberApi.ts
- src/apis/grantableMemberApi.ts
- src/apis/grantedMemberApi.ts
- src/apis/index.ts
- src/apis/paymentStatusApi.ts
- src/apis/pendingMemberApi.ts
- src/types/dtos/member.ts
ResponseDto, RequestDto 타입들 리팩토링 진행했습니다.
> [Refactor/#78] ResponseDto, RequestDto 리팩토링

- src/components/common/Modal/EditInfoModal/AdditionalInfo.tsx
- src/components/common/Modal/EditInfoModal/BasicInfo.tsx
- src/components/common/Modal/EditInfoModal/DiscordInfo.tsx
- src/components/common/Modal/EditInfoModal/index.tsx
- src/hooks/mutations/useEditMemberInfoMutation.ts
- src/utils/validation/index.ts
멤버 정보 수정 모달 코드를 리팩토링했습니다.
다음 항목들 변경했습니다.
- 멤버 정보 수정 모달 내부 컴포넌트명 변경
- validation 객체에 isError, helperText 속성 추가
> [Refactor/#86] 멤버 정보 수정 모달 리팩토링

- src/components/common/Modal/AcceptMemberListModal/index.tsx
- src/components/common/Table/AllMemberInfoTable/AllMemberInfoTableBody.tsx
- src/components/common/Table/AllMemberInfoTable/AllMemberInfoTableHeader.tsx
- src/components/common/Table/GrantableMemberInfoTable/GrantableMemberInfoTableBody.tsx
- src/components/common/Table/GrantableMemberInfoTable/GrantableMemberInfoTableHeader.tsx
- src/components/common/Table/GrantedMemberInfoTable/GrantedMemberInfoTableBody.tsx
- src/components/common/Table/GrantedMemberInfoTable/GrantedMemberInfoTableHeader.tsx
- src/components/common/Table/PaymentStatusInfoTable/PaymentStatusInfoTableBody.tsx
- src/components/common/Table/PaymentStatusInfoTable/PaymentStatusInfoTableHeader.tsx
- src/components/common/Table/PendingMemberInfoTable/PendingMemberInfoTableBody.tsx
- src/components/common/Table/PendingMemberInfoTable/PendingMemberInfoTableHeader.tsx
- src/components/layout/common/Layout.tsx
- src/constants/table.ts
- src/types/entities/table.ts
- src/utils/getTableRatio.ts
테이블 컴포넌트를 리팩토링했습니다.
다음 항목 리팩토링했습니다.
- 명령형 코드 함수형 프로그래밍 방식으로 리팩토링
- 공통 함수로 추출 가능한 부분 리팩토링
> [Refactor/#90] 테이블 컴포넌트 리팩토링

- src/components/common/Table/GrantableMemberInfoTable/GrantableMemberInfoTableBody.tsx
- src/components/common/Table/PaymentStatusInfoTable/PaymentStatusInfoTableBody.tsx
- src/utils/fx/reduce.ts
함수형 프로그래밍 도입으로 인한 에러를 해결했습니다.
reduce 함수 구현체가 잘못되어 테이블 리스트들이 제대로 렌더링되지 않는 문제였습니다.
reduce 함수 수정 후 자잘한 에러 해결했습니다.
> [Bug/#92] 함수형 프로그래밍 도입으로 인한 에러 해결

- src/apis/couponApi.ts
- src/components/common/Header/CouponHeader.tsx
- src/components/common/Modal/CouponModal.tsx
- src/components/common/Modal/EditInfoModal.tsx
- src/components/common/Table/AllMembersInfoTable.tsx
- src/components/common/Table/CouponInfoTable.tsx
- src/constants/common.ts
- src/constants/queryKey.ts
- src/contexts/CouponSearchInfoContext.tsx
- src/hooks/contexts/useCouponSearchInfoState.ts
- src/hooks/mutations/useCreateCouponMutation.ts
- src/hooks/mutations/useDeleteCouponMutation.ts
- src/hooks/queries/useGetIssuedCouponListQuery.ts
- src/pages/CouponPage.tsx
- src/types/dtos/coupon.ts
- src/types/dtos/member.ts
- src/types/entities/member.ts
- src/utils/date.ts
회비 관리 - 쿠폰 관리 페이지 구현했습니다.
아래 사항들 진행했습니다.
- 쿠폰 생성 모달 구현
- 쿠폰 수정 모달 구현
- 쿠폰 회수 api 연결
쿠폰 생성 api 연결은 누락된 dto가 있어 api 수정 후 진행할 예정이고, 수정 api 연결은 아직 개발되지 않은 거 같아 api 개발 이후 진행할 예정입니다.
> [Feature] 회비 관리 - 쿠폰 관리 페이지 구현

- src/components/common/Modal/CouponModal.tsx
- src/components/common/Modal/EditInfoModal.tsx
- src/components/common/Table/AllMembersInfoTable.tsx
- src/components/common/Table/CouponInfoTable.tsx
- src/components/layout/Layout.tsx
- src/constants/table.ts
- src/routes/Router.tsx
디자인 및 기획 변경 사항 반영했습니다.
다음 사항 변경했습니다.
- 쿠폰 관리 페이지 디자인 변경 사항 반영
- 정회원 관리 페이지 멤버 정보 수정 모달 디자인 변경 사항 반영
- 쿠폰 모달 디자인 변경 사항 반영
- 로그아웃 버튼 전 페이지에서 보이게 수정
- 정회원 정보 수정 모달 디자인 수정
> [Chore] 디자인 및 기획 변경 사항 반영

- src/components/common/Table/CouponProvisionInfoTable.tsx
쿠폰 지급 관리 페이지에 상세 모달을 구현해놨었는데, 기획 단에서 삭제되어 반영해뒀습니다
> [Chore] 쿠폰 지급 관리 페이지 상세 모달 삭제

- src/components/common/Modal/CouponModal.tsx
- src/components/common/Table/CouponInfoTable.tsx
쿠폰 관리 페이지에서 조회 api DTO가 변경되어 반영했습니다.
그리고 쿠폰 생성 모달 디자인이 변경되어 이 부분도 함께 반영했습니다.
> [Chore] 쿠폰 관리 페이지 변경된 api 반영 및 쿠폰 생성 모달 디자인 수정

- package.json
- pnpm-lock.yaml
- src/apis/index.ts
- src/components/common/Header/RecruitingRoundHeader.tsx
- src/components/common/Modal/RecruitingRoundInfoModal.tsx
- src/components/common/Table/RecruitingRoundInfoTable.tsx
- src/constants/common.ts
- src/contexts/RecruitingRoundSearchInfoContext.tsx
- src/hooks/contexts/useRecruitingRoundSearchInfoContext.ts
- src/pages/RecruitingRoundPage.tsx
- src/types/entities/member.ts
회비 관리 - 모집 회차 관리 페이지 구현했습니다.
api가 아직 개발 중이라 api 제외하고 구현해놨습니다.
> [Feature] 회비 관리 - 모집 회차 관리 페이지 구현

- src/components/common/Header/PendingMembersHeader.tsx
- src/components/common/Table/AllMembersInfoTable.tsx
- src/components/common/Table/PendingMembersInfoTable.tsx
- src/constants/table.ts
- src/contexts/PendingMembersSearchInfoContext.tsx
- src/types/entities/member.ts
- src/types/entities/table.ts
정회원 관리 페이지처럼 상태 관리쪽 리팩토링하고 자잘한 수정사항 반영했습니다.
> [Refactor] 가입 대기 멤버 관리 페이지 리팩토링

- src/apis/couponApi.ts
- src/apis/recruitingApi.ts
- src/components/common/Header/CouponHeader.tsx
- src/components/common/Header/PaymentStatusHeader.tsx
- src/components/common/Header/RecruitingHeader.tsx
- src/components/common/Header/RecruitingRoundHeader.tsx
- src/components/common/Modal/CreateSemesterInfoModal.tsx
- src/components/common/Modal/EditInfoModal.tsx
- src/components/common/Modal/RecruitingRoundInfoModal.tsx
- src/components/common/Table/CouponInfoTable.tsx
- src/components/common/Table/CouponProvisionInfoTable.tsx
- src/components/common/Table/CouponProvisionMembersInfoTable.tsx
- src/components/common/Table/PaymentStatusInfoTable.tsx
- src/components/common/Table/RecruitingInfoTable.tsx
- src/components/common/Table/RecruitingRoundInfoTable.tsx
- src/contexts/CouponSearchInfoContext.tsx
- src/hooks/contexts/usePaymentStatusSearchInfoContext.ts
- src/hooks/mutations/useRevokeIssuedCouponMutation.ts
- src/hooks/queries/useGetCouponListQuery.ts
- src/routes/Router.tsx
- src/types/dtos/member.ts
회비 관리 - 쿠폰 관리 페이지에서 검색 조건을 삭제하고 헤더에서는 쿠폰 생성 버튼만 남겨두도록 했습니다.
> [Refactor] 회비 관리 - 쿠폰 관리 페이지 검색 조건 삭제

- src/apis/recruitingApi.ts
- src/components/common/Table/RecruitingInfoTable.tsx
- src/constants/queryKey.ts
- src/hooks/queries/useGetRecruitmentsQuery.ts
- src/types/entities/recruiting.ts
모집 관리 - 모집 회차 관리 페이지 조회 api 및 수정 api 연결했습니다.
> [Feature] 모집 관리 - 모집 회차 관리 페이지 조회 api 및 수정 api 연결

- src/apis/recruitmentApi.ts
- src/components/common/Modal/RecruitmentRoundInfoModal.tsx
- src/hooks/mutations/useCreateRecruitmentRoundMutation.ts
- src/hooks/mutations/useEditRecruitmentRoundMutation.ts
> [Feature] 리크루팅 관리 - 모집 회차 관리 페이지 모집 회차 생성 api 연결

- src/apis/paymentStatusApi.ts
- src/components/PaymentStatus/PaymentDetailInfoModal.tsx
- src/components/PaymentStatus/PaymentStatusHeader.tsx
- src/components/PaymentStatus/PaymentStatusInfoTable.tsx
- src/constants/paymentStatus.ts
- src/constants/queryKey.ts
- src/contexts/PaymentStatusContext.tsx
- src/hooks/mutations/useCancelPaymentMutation.ts
- src/hooks/queries/useGetPaymentDetailInfoQuery.ts
- src/hooks/queries/useGetPaymentListQuery.ts
- src/types/entities/payment.ts
- src/utils/validation/formatDate.ts
회비 납부 관리 페이지 구현했습니다.
- 정보 조회 api 연결
- 환불 api 연결
> [Feature] 회비 납부 페이지 구현

- src/hooks/queries/useGetStudyListQuery.ts
- 쿠폰 스터디 필드에서 스터디 오픈 날짜 최신 순으로 정렬하는 것으로 수정합니다.
> [Fix] 쿠폰 스터디 필드에서 스터디 최신 순으로 정렬하는 것으로 수정

- pnpm-lock.yaml
- src/pages/SigninPage.tsx
- vite.config.ts
와우 온보딩인 실행 포트인 5173과 겹쳐서, 포트번호를 5174로 변경합니다.
Proxy 세팅에 변경사항 반영 필요합니다.
> [Fix] 어드민 실행 포트 5174로 변경
